/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PROJECT NAME: Running lights
//
// PLATFORM:     IAR for STM8
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS                10   // Number of tasks that can be active at one time
#define OS_DISABLE_PRIORITY         // old style constant
#define OS_PRIORITY_LEVEL  OS_PRIORITY_DISABLED 

//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------

#define OS_ENABLE_TTIMERS           // Enable task timers (OS_Delay and OS_xxx_Wait_TO)
#define OS_USE_INLINE_TIMER         // Make OS_Timer service as in-line function


//------------------------------------------------------------------------------
// TYPES
//------------------------------------------------------------------------------

#define OS_TIMER_SIZE           2   // Size of all system timers (1, 2 or 4)
#define OS_TTIMER_SIZE          2   // Size of task timers (1, 2 or 4)




#endif
